---
# yaml-language-server: $schema=https://k8s-schemas.home-operations.com/kustomize.toolkit.fluxcd.io/kustomization_v1.json
apiVersion: kustomize.toolkit.fluxcd.io/v1
kind: Kustomization
metadata:
  name: forgejo-runner-codeberg
  namespace: flux-system
spec:
  commonMetadata:
    labels:
      app.kubernetes.io/name: forgejo-runner-codeberg
  interval: 1h
  path: "./k8s/media/apps/forgejo/forgejo-runner-codeberg/app"
  prune: true
  sourceRef:
    kind: OCIRepository
    name: flux-system
    namespace: flux-system
  targetNamespace: forgejo
  timeout: 5m
  wait: false
