module.exports = {
    delay: 20,
    qbittorrentUrl: "http://qbittorrent.media.svc.cluster.local",
    prowlarrUrl: "https://prowlarr.skylab.fi",
    prowlarrApiKey: "{{ .PROWLARR__API_KEY }}",
    prowlarrTag: "cross-seed",
    action: "inject",
    includeEpisodes: true,
    includeNonVideos: true,
    duplicateCategories: true,
    matchMode: "safe",
    skipRecheck: true,
    linkType: "hardlink",
    linkDir: "/mnt/merge/Downloads/qbittorrent/complete/cross-seed",
    dataDirs: [
        "/mnt/merge/Downloads/qbittorrent/complete/prowlarr",
        "/mnt/merge/Downloads/qbitttorrent/complete/radarr",
        "/mnt/merge/Downloads/qbitttorrent/complete/sonarr",
    ],
    outputDir: "/config/xseeds",
    torrentDir: "/config/qBittorrent/BT_backup",
};