---
# yaml-language-server: $schema=https://schemas.k8s.vectorama.fi/postgresql.cnpg.io/scheduledbackup_v1.json
apiVersion: postgresql.cnpg.io/v1
kind: ScheduledBackup
metadata:
  name: daily-backup
  namespace: databases
spec:
  cluster:
    name: postgres16
  schedule: "0 0 0 * * *" # midnight (UTC)
  immediate: true
  backupOwnerReference: self
  method: plugin
  pluginConfiguration:
    name: barman-cloud.cloudnative-pg.io
